name: habit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #Images
  flutter_svg: ^2.2.0

  #Fonts
  google_fonts: ^6.2.1

  # State managment
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  #Firebase Auth
  firebase_auth: ^5.6.1
  firebase_core: ^3.14.0

  #Router
  go_router: ^15.1.3

  #Animation
  shimmer_animation: ^2.2.2

  #OCR
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  google_mlkit_commons: ^0.11.0

  #Navigation Bar
  indicator_bottom_navigationbar: ^0.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/icons/
  

  fonts:
    - family: FugazOne
      fonts:
        - asset: assets/fonts/FugazOne.ttf